Repository nvidia-holoscan/holohub, pull requests merged in 2023-09, with the labels that each got.

#77 Add HoloChat-local App
  applications/holochat_local/.gitignore
  applications/holochat_local/Dockerfile
  applications/holochat_local/Makefile
  applications/holochat_local/README.md
  applications/holochat_local/holochat/build_holoscan_db.py
  applications/holochat_local/holochat/chatbot.py
  applications/holochat_local/holochat/holoscan.png
  applications/holochat_local/holochat/llm.py
  applications/holochat_local/holochat/utils.py
  applications/holochat_local/holochat_demo.gif
Labels: enhancement

#83 HoloChat App: Correct prompts, add documentation, update intro
  applications/holochat_local/Dockerfile
  applications/holochat_local/Makefile
  applications/holochat_local/README.md
  applications/holochat_local/holochat/build_holoscan_db.py
  applications/holochat_local/holochat/chatbot.py
  applications/holochat_local/holochat/llm.py
  applications/holochat_local/holochat/utils.py
Labels: documentation

#85 multiai_endoscopy: fix add_flow for Holoviz when source is AJA
  applications/multiai_endoscopy/cpp/post-proc-cpu/multi_ai.cpp
  applications/multiai_endoscopy/cpp/post-proc-matx-cpu/multi_ai.cpp
  applications/multiai_endoscopy/cpp/post-proc-matx-gpu/multi_ai.cu
  applications/multiai_endoscopy/python/multi_ai.py
Labels: bug

#96 Update Local Llama llama.cpp
  tutorials/local-llama/README.md
Labels: enhancement
