Repository nvidia-holoscan/holohub, pull requests merged in 2023-11, with the labels that each got.

#132 Add --add-volume to launch command
  dev_container
Labels: enhancement

#130 Add Qt application and QtVideoOp.
  applications/CMakeLists.txt
  applications/qt_video_replayer/CMakeLists.txt
  applications/qt_video_replayer/Dockerfile
  applications/qt_video_replayer/README.md
  applications/qt_video_replayer/metadata.json
  applications/qt_video_replayer/qt_holoscan_app.cpp
  applications/qt_video_replayer/qt_holoscan_app.hpp
  applications/qt_video_replayer/qt_video_replayer.cpp
  applications/qt_video_replayer/qt_video_replayer.qml
  applications/qt_video_replayer/screenshot.png
  operators/CMakeLists.txt
  operators/npp_filter/CMakeLists.txt
  operators/npp_filter/README.md
  operators/npp_filter/metadata.json
  operators/npp_filter/npp_filter.cpp
  operators/npp_filter/npp_filter.hpp
  operators/qt_video/CMakeLists.txt
  operators/qt_video/README.md
  operators/qt_video/metadata.json
  operators/qt_video/opengl_renderer.cpp
  operators/qt_video/opengl_renderer.hpp
  operators/qt_video/qt_holoscan_video.cpp
  operators/qt_video/qt_holoscan_video.hpp
  operators/qt_video/qt_video_op.cpp
  operators/qt_video/qt_video_op.hpp
  operators/qt_video/shared_data.hpp
Labels: enhancement

#136 Exact Latency Percentile Value
  tutorials/holoscan_flow_benchmarking/analyze.py
Labels: enhancement

#140 ASR to LLM Application
  .gitignore
  applications/asr_to_llm/Dockerfile
  applications/asr_to_llm/README.MD
  applications/asr_to_llm/asr_to_llm.py
  applications/asr_to_llm/asr_to_llm.yaml
  applications/asr_to_llm/example_output.md
  applications/asr_to_llm/llm.py
  applications/asr_to_llm/metadata.json
  applications/asr_to_llm/requirements.txt
  applications/asr_to_llm/riva_asr.py
  applications/asr_to_llm/streaming_print.py
Labels: enhancement

#150 Mount sound devices for ASR operator
  dev_container
Labels: bug

#152 Documentation update and bug fixes for Holoscan Flow Benchmarking
  tutorials/holoscan_flow_benchmarking/README.md
  tutorials/holoscan_flow_benchmarking/analyze.py
Labels: bug, documentation
