Repository nvidia-holoscan/holohub, pull requests merged in 2024-11, with the labels that each got.

#563 Update dev_container script to support Wayland.
  dev_container
Labels: enhancement

#574 stddev and max got mixed up in v2.3 release benchmarking markdown
  benchmarks/release_benchmarking/release/v2.3.0/v2.3.0.md
Labels: documentation

#587 modified patch application script to be more explicit in CPP files
  benchmarks/holoscan_flow_benchmarking/patch_application.sh
Labels: enhancement

#589 logger.info error in benchmark.py
  benchmarks/holoscan_flow_benchmarking/benchmark.py
Labels: bug
