Repository nvidia-holoscan/holohub, pull requests merged in 2024-08, with the labels that each got.

#458 Bump base container for Holoscan SDK v2.3.0
  dev_container
Labels: dependencies

#459 Bump the Hero card for Holoscan SDK v2.3.0 release
  src/Hero.jsx
Labels: documentation

#468 Doc: Update README badges with latest statistics
  README.md
Labels: documentation

#450 VS Code templates for dev & debug on native environments
  applications/nvidia_nim/nvidia_nim_imaging/README.md
  tutorials/debugging/README.md
  tutorials/debugging/cli_debugging/.gitignore
  tutorials/debugging/cli_debugging/Dockerfile
  tutorials/debugging/cli_debugging/README.md
  tutorials/debugging/cli_debugging/debug_gdb.sh
  tutorials/debugging/cli_debugging/debug_legacy.sh
  tutorials/debugging/cli_debugging/debug_pdb.sh
  tutorials/debugging/cli_debugging/holoscan_sdk_20240723_1.diff
  tutorials/debugging/cli_debugging/metadata.json
  tutorials/debugging/holoscan_container_vscode/.devcontainer/Dockerfile
  tutorials/debugging/holoscan_container_vscode/.devcontainer/devcontainer.json
  tutorials/debugging/holoscan_container_vscode/.devcontainer/initialize-command.sh
  tutorials/debugging/holoscan_container_vscode/.devcontainer/post-start-command.sh
  tutorials/debugging/holoscan_container_vscode/.gitignore
  tutorials/debugging/holoscan_container_vscode/README.md
  tutorials/debugging/holoscan_container_vscode/metadata.json
  tutorials/debugging/holoscan_container_vscode/src/README.md
  tutorials/debugging/holoscan_container_vscode/static/vscode-breakpoint.png
  tutorials/debugging/holoscan_container_vscode/static/vscode-explorer.png
  tutorials/debugging/holoscan_container_vscode/static/vscode-missing-cppdbg.png
  tutorials/debugging/holoscan_container_vscode/static/vscode-run-and-debug.png
  tutorials/debugging/vscode-native/.gitignore
  tutorials/debugging/vscode-native/README.md
  tutorials/debugging/vscode-native/cpp/.gitignore
  tutorials/debugging/vscode-native/cpp/.vscode/launch.json
  tutorials/debugging/vscode-native/cpp/.vscode/settings.json
  tutorials/debugging/vscode-native/cpp/CMakeLists.txt
  tutorials/debugging/vscode-native/cpp/CMakePresets.json
  tutorials/debugging/vscode-native/cpp/src/CMakeLists.txt
  tutorials/debugging/vscode-native/cpp/src/hello_world.cpp
  tutorials/debugging/vscode-native/python/.gitignore
  tutorials/debugging/vscode-native/python/.vscode/launch.json
  tutorials/debugging/vscode-native/python/.vscode/settings.json
  tutorials/debugging/vscode-native/python/pytest.ini
  tutorials/debugging/vscode-native/python/src/hello_world.py
  tutorials/debugging/vscode-native/python/src/requirements.txt
  tutorials/debugging/vscode-native/python/tests/test_hello_world.py
  tutorials/debugging/vscode-native/static/vscode-cmake-statusbar.png
  tutorials/debugging/vscode-native/static/vscode-cpp-breakpoint.png
  tutorials/debugging/vscode-native/static/vscode-cpp-files.png
  tutorials/debugging/vscode-native/static/vscode-cpp-files.xcf
  tutorials/debugging/vscode-native/static/vscode-cpp-holoscan-sdk.png
  tutorials/debugging/vscode-native/static/vscode-python-breakpoint.png
  tutorials/debugging/vscode-native/static/vscode-python-holoscan-sdk.png
Labels: documentation

#466 Enable packaging of the applications using Holoscan CLI
  .gitignore
  CMakeLists.txt
  applications/endoscopy_tool_tracking/README.md
  applications/endoscopy_tool_tracking/cpp/CMakeLists.txt
  applications/endoscopy_tool_tracking/cpp/endoscopy_tool_tracking.yaml
  applications/endoscopy_tool_tracking/cpp/main.cpp
  applications/endoscopy_tool_tracking/cpp/package-app.sh
  applications/endoscopy_tool_tracking/python/CMakeLists.txt
  applications/endoscopy_tool_tracking/python/endoscopy_tool_tracking.py
  applications/endoscopy_tool_tracking/python/endoscopy_tool_tracking.yaml
  applications/endoscopy_tool_tracking/python/package-app.sh
  applications/object_detection_torch/CMakeLists.txt
  applications/object_detection_torch/README.md
  applications/object_detection_torch/main.cpp
  applications/object_detection_torch/object_detection_torch.yaml
  applications/object_detection_torch/package-app.sh
  run
  utilities/bash_utils.sh
Labels: enhancement

#473 App Install - Prevent null variables during a clean build
  applications/endoscopy_tool_tracking/cpp/CMakeLists.txt
  applications/endoscopy_tool_tracking/python/CMakeLists.txt
  applications/object_detection_torch/CMakeLists.txt
Labels: bug

#475 Re-enable default holohub data path for Endoscopy Tool Tracking
  applications/endoscopy_tool_tracking/cpp/main.cpp
  applications/endoscopy_tool_tracking/python/endoscopy_tool_tracking.py
  run
Labels: bug

#481 Update run app command
  operators/advanced_network/README.md
Labels: bug

#485 Update script messages to use build_and_install
  applications/endoscopy_tool_tracking/cpp/package-app.sh
  applications/endoscopy_tool_tracking/python/package-app.sh
  applications/object_detection_torch/package-app.sh
Labels: bug

#487 VSCode - Compound Task for DETT - Set address and worker-address with port
  .vscode/launch.json
  .vscode/tasks.json
  applications/endoscopy_tool_tracking_distributed/python/endoscopy_tool_tracking.py
Labels: bug
