Repository nvidia-holoscan/holohub, pull requests merged in 2024-04, with the labels that each got.

#272 Support passing Condition and Resource arguments as a positional argument to all provided Python operators
  operators/advanced_network/python/adv_network_rx_pybind.cpp
  operators/advanced_network/python/adv_network_tx_pybind.cpp
  operators/emergent_source/python/emergent_source.cpp
  operators/lstm_tensor_rt_inference/python/lstm_tensor_rt_inference.cpp
  operators/openigtlink/python/openigtlink_rx.cpp
  operators/openigtlink/python/openigtlink_tx.cpp
  operators/operator_util.hpp
  operators/orsi/orsi_format_converter/python/format_converter.cpp
  operators/orsi/orsi_segmentation_postprocessor/python/segmentation_postprocessor.cpp
  operators/orsi/orsi_segmentation_preprocessor/python/segmentation_preprocessor.cpp
  operators/orsi/orsi_visualizer/python/orsi_visualizer.cpp
  operators/prohawk_video_processing/python/prohawkop.cpp
  operators/tool_tracking_postprocessor/python/tool_tracking_postprocessor.cpp
  operators/visualizer_icardio/python/visualizer_icardio_pybind.cpp
  operators/yuan_qcap/python/qcap_source.cpp
Labels: enhancement

#278 Update `volume_rendering_xr` Application for Magic Leap 2 v1.5.0
  applications/volume_rendering_xr/.gitignore
  applications/volume_rendering_xr/CMakeLists.txt
  applications/volume_rendering_xr/Dockerfile
  applications/volume_rendering_xr/Dockerfile.base
  applications/volume_rendering_xr/Dockerfile.dev
  applications/volume_rendering_xr/README.md
  applications/volume_rendering_xr/metadata.json
  applications/volume_rendering_xr/scripts/dev-entrypoint.sh
  applications/volume_rendering_xr/thirdparty/magicleap.sh
  applications/volume_rendering_xr/thirdparty/magicleap/MagicLeapRemoteRendering.gpg
  applications/volume_rendering_xr/thirdparty/magicleap/README.txt
  applications/volume_rendering_xr/thirdparty/magicleap/ml_pair.sh
  applications/volume_rendering_xr/thirdparty/magicleap/ml_start.sh
  applications/volume_rendering_xr/thirdparty/magicleap/ml_stop.sh
Labels: enhancement

#280 remove explicit data download step from Orsi application run instructions
  applications/orsi/README.md
Labels: documentation

#262 update ToolTrackingPostprocessorOp for compatibility with distributed apps
  applications/endoscopy_tool_tracking/cpp/main.cpp
  applications/endoscopy_tool_tracking/python/endoscopy_tool_tracking.py
  applications/h264/h264_endoscopy_tool_tracking/main.cpp
  operators/tool_tracking_postprocessor/python/tool_tracking_postprocessor.cpp
  operators/tool_tracking_postprocessor/python/tool_tracking_postprocessor_pydoc.hpp
  operators/tool_tracking_postprocessor/tool_tracking_postprocessor.cpp
  operators/tool_tracking_postprocessor/tool_tracking_postprocessor.hpp
  tutorials/creating-multi-node-applications/scenario2/endoscopy_distributed_app.py
Labels: enhancement

#284 App: Fix for data pollution among volume rendering apps
  applications/volume_rendering_xr/CMakeLists.txt
  applications/volume_rendering_xr/metadata.json
Labels: bug

#286 Doc: Fix URL references from CDash reporting
  tutorials/cuda_mps/README.md
  tutorials/pretrained_foundational_models/self_supervised_training/README.md
Labels: bug, documentation

#287 Op: Enhance `basic_network_rx` Python logging
  operators/basic_network/python/basic_network_rx.py
Labels: enhancement

#293 App: Add third party links to Lidar app README
  applications/velodyne_lidar_app/cpp/README.md
Labels: documentation, enhancement

#292 Homepage: Add "Run Locally" button to each application card
  src/App.jsx
  src/Card.jsx
Labels: enhancement

#294 Homepage: Bump for Holoscan SDK v2.0.0 release
  src/Hero.jsx
Labels: enhancement

#295 Doc: Fix broken URL link in lidar operator README
  operators/velodyne_lidar/cpp/README.md
Labels: bug
