Repository nvidia-holoscan/holohub, pull requests merged in 2024-12, with the labels that each got.

#611 Small enhancements to ANO bench configs
  applications/adv_networking_bench/adv_networking_bench_default_rx.yaml
  applications/adv_networking_bench/adv_networking_bench_default_tx.yaml
  applications/adv_networking_bench/adv_networking_bench_default_tx_rx.yaml
  applications/adv_networking_bench/adv_networking_bench_doca_tx_rx.yaml
  applications/adv_networking_bench/adv_networking_bench_rmax_rx.yaml
Labels: enhancement

#590 Endoscopy tool tracking not working with MPS after PR 550 note
  tutorials/cuda_mps/README.md
Labels: documentation

#615 Update PyTorch Install for VILA_Live and Florence 2
  applications/florence-2-vision/Dockerfile
  applications/florence-2-vision/requirements.txt
  applications/vila_live/Dockerfile
  applications/vila_live/requirements.txt
Labels: bug

#639 Improvements to run list and run build
  README.md
  run
Labels: enhancement

#644 Fix typo in Florence-2 vision readme.
  applications/florence-2-vision/README.md
Labels: documentation
