Repository nvidia-holoscan/holohub, pull requests merged in 2024-07, with the labels that each got.

#290 App: Distributed Endoscopy Tool Tracking in three fragments
  applications/CMakeLists.txt
  applications/endoscopy_tool_tracking_distributed/CMakeLists.txt
  applications/endoscopy_tool_tracking_distributed/README.md
  applications/endoscopy_tool_tracking_distributed/cpp/CMakeLists.txt
  applications/endoscopy_tool_tracking_distributed/cpp/README.md
  applications/endoscopy_tool_tracking_distributed/cpp/endoscopy_tool_tracking.yaml
  applications/endoscopy_tool_tracking_distributed/cpp/main.cpp
  applications/endoscopy_tool_tracking_distributed/cpp/metadata.json
  applications/endoscopy_tool_tracking_distributed/docs/app_endoscopy.png
  applications/endoscopy_tool_tracking_distributed/docs/workflow_tool_tracking_replayer.png
  applications/endoscopy_tool_tracking_distributed/python/CMakeLists.txt
  applications/endoscopy_tool_tracking_distributed/python/README.md
  applications/endoscopy_tool_tracking_distributed/python/cloud_inference_fragment.py
  applications/endoscopy_tool_tracking_distributed/python/endoscopy_tool_tracking.py
  applications/endoscopy_tool_tracking_distributed/python/endoscopy_tool_tracking.yaml
  applications/endoscopy_tool_tracking_distributed/python/metadata.json
  applications/endoscopy_tool_tracking_distributed/python/video_input_fragment.py
  applications/endoscopy_tool_tracking_distributed/python/viz_fragment.py
Labels: enhancement

#418 Ignore HOME files in Git tracking
  .gitignore
Labels: enhancement

#411 Add examples and document for interoperability with other libraries.
  codespell.txt
  tutorials/integrate_external_libs_into_pipeline/README.md
  tutorials/integrate_external_libs_into_pipeline/cuda_example.py
  tutorials/integrate_external_libs_into_pipeline/cupy_example.py
Labels: documentation

#437 Specify a version of OpenCV to use to avoid breaking changes
  applications/endoscopy_depth_estimation/Dockerfile
Labels: bug

#436 basic_network Python app - handle unavailable parameter values in HSDK 2.1
  applications/basic_networking_ping/README.md
  applications/basic_networking_ping/cpp/metadata.json
  applications/basic_networking_ping/python/CMakeLists.txt
  applications/basic_networking_ping/python/basic_networking_ping.py
  applications/basic_networking_ping/python/metadata.json
  operators/basic_network/python/basic_network_rx.py
  operators/basic_network/python/basic_network_tx.py
Labels: bug

#438 Remove arguments and use env var for data input
  applications/endoscopy_tool_tracking_distributed/cpp/README.md
  applications/endoscopy_tool_tracking_distributed/cpp/main.cpp
  applications/endoscopy_tool_tracking_distributed/cpp/metadata.json
  applications/endoscopy_tool_tracking_distributed/python/README.md
  applications/endoscopy_tool_tracking_distributed/python/endoscopy_tool_tracking.py
  applications/endoscopy_tool_tracking_distributed/python/metadata.json
  applications/endoscopy_tool_tracking_distributed/python/video_input_fragment.py
Labels: bug

#442 Fix Distributed Endoscopy Tool Tracking Test Failures
  applications/endoscopy_tool_tracking_distributed/Dockerfile
  applications/endoscopy_tool_tracking_distributed/cpp/CMakeLists.txt
  applications/endoscopy_tool_tracking_distributed/cpp/main.cpp
  applications/endoscopy_tool_tracking_distributed/cpp/metadata.json
  applications/endoscopy_tool_tracking_distributed/python/CMakeLists.txt
  applications/endoscopy_tool_tracking_distributed/python/endoscopy_tool_tracking.py
  applications/endoscopy_tool_tracking_distributed/python/metadata.json
Labels: bug
